apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: proxy
          image: krushnaprakash/proxy
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
