apiVersion: v1
kind: pod
metadata:
  name: my-pod
spec:
  containers:
      - name: my-pod-container
        image: nginx
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
            
      - name: my-second-container
        image: tomcat
        ports:
          - name: java
            containerPort: 8080
            protocol: TCP 
